version: '3.5'

services:
    broker:
        command: confluent broker
        container_name: broker
        depends_on:
            - zookeeper
        dns: 10.1.3.1
        dns_search: home
        domainname: home
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            JMX_PORT: 1099
            KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP:?}
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOST_IP:?}:9092
            KAFKA_BROKER_ID: ${KAFKA_ID:?}
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_NUM_PARTITIONS: 1
            KAFKA_ZOOKEEPER_CONNECT: ${ZOOKEEPER_HOSTS:?}
            ZOOKEEPER_TIMEOUT: 6000
        hostname: broker.s4
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/confluent/${CONFLUENT_VERSION:-5.3.2}:${CONTAINER_TAG:-85e257c2f76aeabc22e0aa0e64502e029bb15ae7e269cdf4043896b63966ee25}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        links:
           - zookeeper
        networks:
            - kafka-net
        ports:
            - "1099:1099"
            - "9092:9092"
        restart: unless-stopped
        volumes:
            - ./kafka-broker/data:/usr/local/kafka/data
            - ./kafka-broker/logs:/usr/local/kafka/logs
            - ./kafka-broker/log:/var/log

    zookeeper:
#        command: kafka zookeeper
        command: confluent zookeeper
        container_name: zookeeper
        dns: 10.1.3.1
        dns_search: home
        domainname: home
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            JMX_PORT: 1299
            ZOOKEEPER_MY_ID: ${KAFKA_ID:?}
            ZOOKEEPER_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 10
            ZOOKEEPER_SYNC_LIMIT: 5
        hostname: zookeeper.s4
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/confluent/${CONFLUENT_VERSION:-5.3.2}:${CONTAINER_TAG:-85e257c2f76aeabc22e0aa0e64502e029bb15ae7e269cdf4043896b63966ee25}
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "3"
        networks:
            - kafka-net
        ports:
            - "1299:1299"
            - "2181:2181"
        restart: unless-stopped
        volumes:
            - ./kafka-zookeeper/data:/usr/local/kafka/data
            - ./kafka-zookeeper/logs:/usr/local/kafka/logs 
            - ./kafka-zookeeper/log:/var/log

networks:
   kafka-net:
       name: kafka-container-net
